### ISSUE TITLE
[Bug Report] Tokenization utils don't work on LLaMA

### ISSUE THREAD

**Issue by neelnanda-io** [neelnanda-io/TransformerLens#373] opened 2023-08-26 11:24 UTC
**Describe the bug**
The LLaMA tokenizer is weird. Notably, when encoding it will _always_ prepend a space (to the point of creating an additional prepended space token), while when decoding it will _never_ prepend a space to the first token. And it does not recognise the BOS token (\<s\>) when inside text to be tokenized. 

There's a range of bugs I've noticed:

- model.to_tokens with prepend_bos=True maps eg " basketball" to [[529 (<), 29879 (s), 29958 (>), 20305 ( basketball)]] because it adds the _string_ BOS token (\<s\>) but the tokenizer doesn't recognise this in the input.
- prepend_bos=False will implicitly prepend a space, either returning an extra space token prepended or a space token. 
- Accordingly, `model.to_single_token` is broken re space prepending
- `model.to_str_tokens` doesn't have spaces prepended even if appropriate, and prepend_bos also behaves badly.

I'm sure there's more!

There's some hacky ways to get round this, notably by prepending a non-BOS dummy token like " |" (891) when encoding or decoding and then removing the resulting token from the output, we can recover sensible behaviour around spaces. 

I've written some hacky personal utils that somewhat work. It'd be great to add flags to the tokenization utils in HookedTransformer to use some of these (or, ideally, do something more principled!)

```
def decode_single_token(integer):
    # To recover whether the tokens begins with a space, we need to prepend a token to avoid weird start of string behaviour
    return tokenizer.decode([891, integer])[1:]
def to_str_tokens(tokens):
    if isinstance(tokens, str):
        tokens = to_tokens(tokens)
    if isinstance(tokens, torch.Tensor):
        if len(tokens.shape)==2:
            assert tokens.shape[0]==1
            tokens = tokens[0]
        tokens = tokens.tolist()
    return [decode_single_token(token) for token in tokens]
def to_string(tokens):
    if isinstance(tokens, torch.Tensor):
        if len(tokens.shape)==2:
            assert tokens.shape[0]==1
            tokens = tokens[0]
        tokens = tokens.tolist()
    return tokenizer.decode([891]+tokens)[1:]
def to_tokens(string, prepend_bos=True):
    string = "|"+string
    # The first two elements are always [BOS (1), " |" (891)]
    tokens = tokenizer.encode(string)
    if prepend_bos:
        return torch.tensor(tokens[:1] + tokens[2:]).cuda()
    else:
        return torch.tensor(tokens[2:]).cuda()

def to_single_token(string):
    assert string[0]==" ", f"Expected string to start with space, got {string}"
    string = string[1:]
    tokens = tokenizer.encode(string)
    assert len(tokens)==2, f"Expected 2 tokens, got {len(tokens)}: {tokens}"
    return tokens[1]
```

**Comment by soheeyang** [comment] 2023-08-28 22:45
I think some of the issues might be related to https://github.com/huggingface/transformers/pull/24565. Did you find the warning message `You are using the legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This means that tokens that come after special tokens will not be properly handled. We recommend you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565` while loading the tokenizer?

**Comment by soheeyang** [comment] 2023-08-28 23:01
Do you still have this issue? I found and fixed the issues with bos prepending in https://github.com/neelnanda-io/TransformerLens/pull/370.

**Comment by soheeyang** [comment] 2023-08-28 23:12
> Do you still have this issue? I found and fixed the issues with bos prepending in #370.

After this PR, I found out that there is a simpler way of calling `AutoTokeenizer.from_pretrained(..., add_bos_token=False)`, though. 😂 I'd be happy to change the code that way.

**Comment by soheeyang** [comment] 2023-08-31 12:18
> > Do you still have this issue? I found and fixed the issues with bos prepending in #370.
> 
> After this PR, I found out that there is a simpler way of calling `AutoTokeenizer.from_pretrained(..., add_bos_token=False)`, though. 😂 I'd be happy to change the code that way.

This change cannot be made until the bug https://github.com/huggingface/transformers/issues/25886 in the OPT tokenizers is fixed from the `transformers` library.

**Comment by soheeyang** [comment] 2023-08-31 13:14
> Do you still have this issue? I found and fixed the issues with bos prepending in #370.

Oh, wow, I see the issue now. The double bos prepending issue is fixed with #370, but the problem is that **the behavior of LLaMA tokenizer becomes different when bos token is manually added.**

```python3
print('when bos token is automatically added:')
tokenizer_with_bos= AutoTokenizer.from_pretrained(MODEL_PATH, add_bos_token=True)
print(tokenizer_with_bos.encode('Italy'))
print([tokenizer_with_bos.decode(t) for t in tokenizer_with_bos.encode('Italy')])

print('when bos token is manually added:')
tokenizer_without_bos = AutoTokenizer.from_pretrained(MODEL_PATH, add_bos_token=False)
print(tokenizer_without_bos.encode('<s>Italy'))
print([tokenizer_with_bos.decode(t) for t in tokenizer_without_bos.encode('<s>Italy')])
```

@ArthurZucker is this another bug of LLaMA tokenizer that should be fixed, or is this behaviour somehow intended?

**Comment by ArthurZucker** [comment] 2023-08-31 13:20
This is intended. When you manually add a BOS, you change the sentence that is passed to the tokenizer. 
```python
>>> tokenizer_with_bos= AutoTokenizer.from_pretrained("huggyllama/llama-7b", add_bos_token=True)
>>> print(tokenizer_with_bos.tokenize('Italy'))
['▁Italy']

>>> tokenizer_without_bos = AutoTokenizer.from_pretrained("huggyllama/llama-7b", add_bos_token=False)
>>> print(tokenizer_without_bos.tokenize('<s>Italy'))
['▁<s>', 'Ital', 'y']
```
As you can see, the automatic addition adds the `bos_tokens_id` to the already encoded `ids`. In this case, the prefix space was thus added to `Italy`. Thus the encoding is `'▁Italy'` (which IMO is goos) .

**Comment by soheeyang** [comment] 2023-08-31 13:22
> This is intended. When you manually add a BOS, you change the sentence that is passed to the tokenizer.
> 
> ```python
> >>> tokenizer_with_bos= AutoTokenizer.from_pretrained("huggyllama/llama-7b", add_bos_token=True)
> >>> print(tokenizer_with_bos.tokenize('Italy'))
> ['▁Italy']
> 
> >>> tokenizer_without_bos = AutoTokenizer.from_pretrained("huggyllama/llama-7b", add_bos_token=False)
> >>> print(tokenizer_without_bos.tokenize('<s>Italy'))
> ['▁<s>', 'Ital', 'y']
> ```
> 
> As you can see, the automatic addition adds the `bos_tokens_id` to the already encoded `ids`. In this case, the prefix space was thus added to `Italy`. Thus the encoding is `'▁Italy'` (which IMO is goos) .

I see, thank you so much for the clarification!

**Comment by ArthurZucker** [comment] 2023-08-31 13:35
별말씀을요!

**Closed** 2023-10-10 19:10 UTC
